import { GalleryHorizontalEnd } from "lucide-react";
import { ComingSoon } from "@/components/sections/ComingSoon";

/** Examples Gallery — real generated script showcases ship in Part 6. */
export default function Examples() {
  return (
    <ComingSoon
      icon={GalleryHorizontalEnd}
      eyebrow="Examples Gallery"
      title="Examples Gallery — Coming Soon"
      description="Browse real Hindi animation scripts generated by AniViora Craft — thriller, moral stories, horror, comedy and devotional genres with full scene breakdowns."
      partNote="Arriving with the Generator in Part 6"
    />
  );
}
